spring.application.name=LearningRabbitMQ
spring.output.ansi.enabled=ALWAYS

#Connecting to RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=queue_demo
rabbitmq.exchange.name=exchange_demo
rabbitmq.routing.key=routing_key_demo

rabbitmq.jsion.queue.name=jsion_queue_demo
rabbitmq.jsion.routing.key=routing_key_jsion_demo


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medicore.owner@gmail.com
spring.mail.password=qtby nmsh tthp qctk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true